openapi: 3.1.0
info:
  title: UniCore HTTP API
  description: ''
  license:
    name: Apache 2.0
  version: 0.0.0-semantically-released
servers:
- url: http://localhost:3033
  description: Local development
paths:
  /v0/connections:
    get:
      tags:
      - Connections
      summary: List all connections
      description: List all available connections.
      operationId: get_all_connections
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/GetConnectionsEndpointRequest'
        required: true
      responses:
        '200':
          description: All connections retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ConnectionView'
    post:
      tags:
      - Connections
      summary: Add a Connection
      description: Adds a new connection based on the provided domain.
      operationId: add_connection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddConnectionEndpointRequest'
        required: true
      responses:
        '201':
          description: Connection added successfully
          headers:
            Location:
              schema:
                type: string
              description: URI of the newly created connection
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConnectionView'
  /v0/connections/accept-pending-changes:
    post:
      tags:
      - Connections
      summary: Accept Pending Changes
      description: Accept pending changes to a connection.
      operationId: accept_connection_changes
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptConnectionChangesRequest'
        required: true
      responses:
        '200':
          description: ''
  /v0/connections/remove-connection:
    post:
      tags:
      - Connections
      summary: Remove Connection
      description: Removes a connection
      operationId: remove_connection
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveConnectionRequest'
        required: true
      responses:
        '200':
          description: ''
  /v0/connections/sync-connection:
    post:
      tags:
      - Connections
      summary: Sync connection by ID
      description: Sync the latest version of a connection by its unique identifier.
      operationId: sync_connection_by_id
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SyncConnectionRequest'
        required: true
      responses:
        '200':
          description: ''
  /v0/connections/{id}:
    get:
      tags:
      - Connections
      summary: Get connection by ID
      description: Retrieve a specific connection by its unique identifier.
      operationId: get_connection_by_id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: ''
  /v0/templates/create-template:
    post:
      tags:
      - Library
      - Templates
      summary: Create a new template
      description: Creates a new template which can be used to issue credentials.
      operationId: create_template
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTemplateEndpointRequest'
            examples:
              Standard template:
                description: A simple example that will issue credentials in the W3C Verifiable Credentials Data Model v1.1 format.
                value:
                  title: Standard template
                  credentialFormat: w3c_vc_data_model_v1-1
                  holderType: individual
        required: true
      responses:
        '201':
          description: New template created successfully
          headers:
            Location:
              schema:
                type: string
              description: The path of the newly created template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
  /v0/templates/duplicate-template:
    post:
      tags:
      - Library
      - Templates
      summary: Duplicate existing template
      description: Creates a duplicate of an existing template.
      operationId: duplicate_template
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DuplicateTemplateEndpointRequest'
            example:
              sourceTemplateId: 91fc790f-d876-4827-9a9d-0fb0f6766dca
        required: true
      responses:
        '201':
          description: Duplicate created successfully
          headers:
            Location:
              schema:
                type: string
              description: The path of the newly created template
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
        '422':
          description: Source Template Not Found
  /v0/templates/get-all-templates:
    get:
      tags:
      - Library
      - Templates
      summary: List all templates
      description: List all available templates.
      operationId: get_all_templates
      responses:
        '200':
          description: All templates retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Template'
  /v0/templates/{template_id}:
    get:
      tags:
      - Library
      - Templates
      summary: Get template by ID
      description: Retrieve a specific template by its ID.
      operationId: get_template_by_id
      parameters:
      - name: template_id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Template retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Template'
components:
  schemas:
    AcceptConnectionChangesRequest:
      type: object
      properties:
        id:
          type: string
    AddConnectionEndpointRequest:
      type: object
      properties:
        domain:
          type: string
    ConnectionDisplayProperties:
      type: object
      properties:
        locale:
          type:
          - string
          - 'null'
        logo:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/LogoProperties'
        name:
          type:
          - string
          - 'null'
    ConnectionView:
      type: object
      required:
      - id
      - dids
      properties:
        dids:
          type: array
          items:
            type: string
        display:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/ConnectionDisplayProperties'
        domain:
          type:
          - string
          - 'null'
          format: uri
        first_interacted:
          type:
          - string
          - 'null'
          format: date-time
        id:
          type: string
        last_interacted:
          type:
          - string
          - 'null'
          format: date-time
        pending_changes:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/PendingChanges'
    CreateTemplateEndpointRequest:
      type: object
      properties:
        creator:
          type:
          - string
          - 'null'
          default: null
        credentialFormat:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/CredentialFormat'
          default: null
        description:
          type:
          - string
          - 'null'
          default: null
        display:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/Display'
          default: null
        holderType:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/HolderType'
          default: null
        schema: {}
        status:
          oneOf:
          - $ref: '#/components/schemas/Status'
          default: draft
        tags:
          type: array
          items:
            type: string
          default: []
        title:
          type:
          - string
          - 'null'
          default: null
        type:
          type: array
          items:
            type: string
          default: []
        visibility:
          oneOf:
          - $ref: '#/components/schemas/Visibility'
          default: private
    CredentialFormat:
      type: string
      enum:
      - w3c_vc_data_model_v1-1
      - w3c_vc_data_model_v2-0
      - open_badges_3-0
    Display:
      type: object
      required:
      - name
      properties:
        logo:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/Logo'
        name:
          type: string
    DuplicateTemplateEndpointRequest:
      type: object
      required:
      - sourceTemplateId
      properties:
        sourceTemplateId:
          type: string
    GetConnectionsEndpointRequest:
      type: object
      properties:
        did:
          type:
          - string
          - 'null'
        display:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/ConnectionDisplayProperties'
        domain:
          type:
          - string
          - 'null'
    HolderType:
      type: string
      enum:
      - individual
      - organization
    Logo:
      type: object
      required:
      - uri
      properties:
        alt_text:
          type:
          - string
          - 'null'
        uri:
          type: string
    LogoProperties:
      type: object
      properties:
        alt_text:
          type:
          - string
          - 'null'
        uri:
          type:
          - string
          - 'null'
          format: uri
    PendingChanges:
      type: object
      required:
      - dids
      properties:
        dids:
          type: array
          items:
            type: string
        display:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/ConnectionDisplayProperties'
    RemoveConnectionRequest:
      type: object
      properties:
        id:
          type: string
    Status:
      type: string
      enum:
      - draft
      - published
      - archived
      - deleted
    SyncConnectionRequest:
      type: object
      properties:
        id:
          type: string
    Template:
      type: object
      description: Data transfer object for Templates.
      required:
      - id
      - tags
      - status
      - visibility
      - type
      properties:
        creator:
          type:
          - string
          - 'null'
        credentialFormat:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/CredentialFormat'
        description:
          type:
          - string
          - 'null'
        display:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/Display'
        holderType:
          oneOf:
          - type: 'null'
          - $ref: '#/components/schemas/HolderType'
        id:
          type: string
        modifiedAt:
          type:
          - string
          - 'null'
        schema: {}
        sourceTemplateId:
          type:
          - string
          - 'null'
        status:
          $ref: '#/components/schemas/Status'
        tags:
          type: array
          items:
            type: string
        title:
          type:
          - string
          - 'null'
        type:
          type: array
          items:
            type: string
        visibility:
          $ref: '#/components/schemas/Visibility'
    Visibility:
      type: string
      enum:
      - private
      - public
tags:
- name: Connections
  description: Manage trusted connections.
- name: Library
  description: Manage your own templates, browse and import external templates.
- name: Templates
  description: Create and manage templates which provide the structure for credentials to be issued.
externalDocs:
  url: https://docs.impierce.com/unicore
  description: Official UniCore documentation
