[package]
name = "shared-kernel"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
async-trait.workspace = true
chrono = { version = "0.4", features = ["serde"] }
convert_case = "0.11"
cqrs-es = "0.5"
strum = { version = "0.28", features = ["derive"] }
tokio.workspace = true
tracing.workspace = true
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }

[lints]
workspace = true

[features]
default = []
test-utils = []
