[workspace]
resolver = "2"
members = [
    "agent_api_http",
    "agent_application",
    "agent_authorization",
    "agent_event_publisher_http",
    "agent_event_publisher_nats",
    "agent_holder",
    "agent_identity",
    "agent_issuance",
    "agent_library",
    "agent_macros",
    "agent_secret_manager",
    "agent_shared",
    "agent_store",
    "agent_verification",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.76.0"
publish = false

[workspace.dependencies]
siopv2 = { git = "https://github.com/impierce/openid4vc", rev = "99fc7be" }
oid4vci = { git = "https://github.com/impierce/openid4vc", rev = "99fc7be" }
oid4vc-core = { git = "https://github.com/impierce/openid4vc", rev = "99fc7be" }
oid4vc-manager = { git = "https://github.com/impierce/openid4vc", rev = "99fc7be" }
oid4vp = { git = "https://github.com/impierce/openid4vc", rev = "99fc7be" }

anyhow = "1.0"
async-std = { version = "1.5", features = ["attributes", "tokio1"] }
async-trait = "0.1"
axum = "0.8"
base64 = "0.22"
chrono = { version = "0.4", features = ["serde"] }
cqrs-es = "0.4.12"
derivative = "2.2"
futures = "0.3"
identity_core = { git = "https://github.com/iotaledger/identity", tag = "v1.6.0-beta.7" }
identity_credential = { git = "https://github.com/iotaledger/identity", tag = "v1.6.0-beta.7", default-features = false, features = [
    "validator",
    "credential",
    "presentation",
    "domain-linkage",
] }
identity_did = { git = "https://github.com/iotaledger/identity", tag = "v1.6.0-beta.7" }
identity_document = { git = "https://github.com/iotaledger/identity", tag = "v1.6.0-beta.7" }
identity_iota = { git = "https://github.com/iotaledger/identity", tag = "v1.6.0-beta.7" }
identity_storage = { git = "https://github.com/iotaledger/identity", tag = "v1.6.0-beta.7" }
identity_verification = { git = "https://github.com/iotaledger/identity", tag = "v1.6.0-beta.7", default-features = false }
iota-sdk = { git = "https://github.com/iotaledger/iota", package = "iota-sdk", tag = "v1.6.1" }
# TODO: Check if this is still needed.
iota-sdk-legacy = { version = "1.0", package = "iota-sdk", default-features = false, features = [
    "tls",
    "client",
    "stronghold",
] }
jsonwebtoken = "9.3"
lazy_static = "1.4"
mime = { version = "0.3" }
oauth_tsl = { git = "https://github.com/impierce/oauth-token-status-list", rev = "0aa0228" }
once_cell = { version = "1.19" }
product_common = { git = "https://github.com/iotaledger/product-core", tag = "v0.8.2", package = "product_common", features = [
    "gas-station",
    "default-http-client",
] }
rand = "0.9"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }
rstest = "0.22"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = { version = "1.0" }
serde_json_path_to_error = { version = "0.1" }
serde_urlencoded = "0.7"
serde_with = "3.13"
strum = "0.26"
strum_macros = "0.26"
temp-env = "0.3"
thiserror = "1.0"
tokio = { version = "1.46", features = ["full"] }
tower = { version = "0.4" }
tower-http = { version = "0.6", features = ["cors", "trace"] }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = ["json", "env-filter"] }
tracing-test = { version = "0.2" }
url = "2.5"
uuid = { version = "1.4", features = ["v4", "fast-rng", "serde"] }
wiremock = "0.6"
