[package]
name = "agent_store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agent_holder = { path = "../agent_holder" }
agent_identity = { path = "../agent_identity" }
agent_issuance = { path = "../agent_issuance" }
agent_shared = { path = "../agent_shared" }
agent_verification = { path = "../agent_verification" }

async-trait.workspace = true
cqrs-es.workspace = true
mongodb = "3.2"
mongo-es = { git = "https://github.com/impierce/mongo-es", rev = "f75b93e" }
postgres-es = "0.4.12"
serde_json.workspace = true
sqlx = { version = "0.8", features = [
    "postgres",
    "runtime-tokio-rustls",
    "json",
] }
tokio.workspace = true
