[package]
name = "agent_store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agent_authorization = { path = "../agent_authorization" }
agent_holder = { path = "../agent_holder" }
agent_identity = { path = "../agent_identity" }
agent_issuance = { path = "../agent_issuance" }
agent_library = { path = "../agent_library" }
agent_shared = { path = "../agent_shared" }
agent_verification = { path = "../agent_verification" }

async-trait.workspace = true
cqrs-es.workspace = true
mongo-es = "0.3"
postgres-es = "0.4.12"
serde_json.workspace = true
shared-kernel.workspace = true
sqlx = { version = "0.8", features = [
    "postgres",
    "runtime-tokio-rustls",
    "json",
] }
tokio.workspace = true

[dev-dependencies]
agent_secret_manager = { path = "../agent_secret_manager", features = ["test_utils"] }
