[package]
name = "agent_issuance"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
agent_library = { path = "../agent_library" }
agent_shared = { path = "../agent_shared" }
agent_secret_manager = { path = "../agent_secret_manager" }

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
cqrs-es.workspace = true
chrono.workspace = true
derivative.workspace = true
identity_core.workspace = true
identity_credential.workspace = true
jsonwebtoken.workspace = true
lazy_static.workspace = true
oauth_tsl.workspace = true
oid4vci.workspace = true
oid4vc-core.workspace = true
rand.workspace = true
reqwest.workspace = true
sd-jwt.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
utoipa.workspace = true
uuid.workspace = true

# `test_utils` dependencies
once_cell = { workspace = true, optional = true }
rstest = { workspace = true, optional = true }

[dev-dependencies]
agent_holder = { path = "../agent_holder", features = ["test_utils"] }
agent_issuance = { path = ".", features = ["test_utils"] }
agent_secret_manager = { path = "../agent_secret_manager", features = [
    "test_utils",
] }
agent_shared = { path = "../agent_shared", features = ["test_utils"] }
agent_store = { path = "../agent_store" }
async-std.workspace = true
serial_test = "3.0"
tracing-test.workspace = true

[features]
test_utils = ["dep:once_cell", "dep:rstest"]
