[package]
name = "agent_application"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
agent_api_http = { path = "../agent_api_http" }
agent_authorization = { path = "../agent_authorization" }
agent_event_publisher_http = { path = "../agent_event_publisher_http" }
agent_event_publisher_nats = { path = "../agent_event_publisher_nats" }
agent_holder = { path = "../agent_holder" }
agent_identity = { path = "../agent_identity" }
agent_issuance = { path = "../agent_issuance" }
agent_library = { path = "../agent_library" }
agent_secret_manager = { path = "../agent_secret_manager" }
agent_shared = { path = "../agent_shared" }
agent_store = { path = "../agent_store" }
agent_verification = { path = "../agent_verification" }
verification-authorization = { path = "../infrastructure/adapters/verification-authorization" }

anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
did_manager = { git = "https://github.com/impierce/did-manager", rev = "cbf2993" }
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
shared-kernel.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true
