# List of Subject Syntax Types (DID Methods) supported by UniCore. The first item in the list is the default Syntax Type,
# meaning UniCore will use its identifier belonging to this type by default.
subject_syntax_types_supported:
  - did:jwk
  - did:key
  - did:iota:rms

# List of supported signing algorithms for ID Tokens, Request Objects, and Verifiable Credentials. As of now, UniCore
# only supports EdDSA.
signing_algorithms_supported: &signing_algorithms_supported
  - EdDSA
id_token_signing_alg_values_supported: *signing_algorithms_supported
request_object_signing_alg_values_supported: *signing_algorithms_supported
vp_formats:
  jwt_vc_json:
    alg: *signing_algorithms_supported
  jwt_vp_json:
    alg: *signing_algorithms_supported

# These display parameters can be used by identity Wallets to display interactions with UniCore.
display:
  # This value will also be used in the SIOPv2/OID4VP `client_metadata`'s `client_name` property.
  - name: UniCore
    locale: en
    logo:
      # This value will also be used in the SIOPv2/OID4VP `client_metadata`'s `logo_uri` property.
      uri: https://impierce.com/images/logo-blue.png
      alt_text: UniCore Logo
 