[package]
name = "agent_holder"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
agent_shared = { path = "../agent_shared" }
agent_secret_manager = { path = "../agent_secret_manager" }

async-trait.workspace = true
base64.workspace = true
cqrs-es.workspace = true
identity_core.workspace = true
identity_credential.workspace = true
jsonwebtoken.workspace = true
oid4vci.workspace = true
oid4vc-core.workspace = true
serde.workspace = true
serde_json.workspace = true
shared-kernel.workspace = true
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tracing.workspace = true
utoipa.workspace = true
uuid.workspace = true

# `test_utils` dependencies
rstest = { workspace = true, optional = true }

[dev-dependencies]
agent_api_http = { path = "../agent_api_http", features = ["test_utils"] }
agent_authorization = { path = "../agent_authorization", features = [
    "test_utils",
] }
agent_holder = { path = ".", features = ["test_utils"] }
agent_issuance = { path = "../agent_issuance", features = ["test_utils"] }
agent_library = { path = "../agent_library", features = ["test_utils"] }
agent_secret_manager = { path = "../agent_secret_manager", features = [
    "test_utils",
] }
agent_shared = { path = "../agent_shared", features = ["test_utils"] }
agent_store = { path = "../agent_store" }

async-std.workspace = true
axum.workspace = true
lazy_static.workspace = true
mime.workspace = true
names = { version = "0.14", default-features = false }
reqwest.workspace = true
rand.workspace = true
serial_test = "3.0"
temp-env.workspace = true
tokio.workspace = true
tower.workspace = true
tracing-test.workspace = true

[features]
test_utils = ["dep:rstest"]
