[package]
name = "agent_identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agent_shared = { path = "../agent_shared" }
agent_secret_manager = { path = "../agent_secret_manager" }

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
cqrs-es.workspace = true
derivative.workspace = true
did-jwk-extern = { version = "0.1.1", package = "did-jwk" }
did-key-extern = { version = "0.2.2", package = "did-method-key" }
identity_credential.workspace = true
identity_core.workspace = true
identity_did.workspace = true
identity_document.workspace = true
identity_storage.workspace = true
identity_iota.workspace = true
iota-sdk.workspace = true
itertools = "0.14"
jsonwebtoken.workspace = true
oid4vc-core.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
ssi-dids = "0.1.1"
ssi-jwk = "0.1.2"
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
urlencoding = "2.1"
uuid.workspace = true
secret-storage = { git = "https://github.com/iotaledger/secret-storage", tag = "v0.3.0" }
iota_interaction = { git = "https://github.com/iotaledger/product-core.git", tag = "v0.2.1", package = "iota_interaction" }
iota_interaction_ts = { git = "https://github.com/iotaledger/product-core.git", tag = "v0.2.1", package = "iota_interaction_ts" }
product_common = { git = "https://github.com/iotaledger/product-core.git", tag = "v0.2.1", package = "product_common" }
# did_manager_identity_stronghold_ext = { git = "https://github.com/impierce/did-manager", branch = "feat/stronghold-ext-rebased", package = "identity_stronghold_ext" }
did_manager_identity_stronghold_ext = { path = "../../did-manager/identity_stronghold_ext", package = "identity_stronghold_ext" }

# `test_utils` dependencies
futures = { workspace = true, optional = true }
rstest = { workspace = true, optional = true }

[dev-dependencies]
agent_api_rest = { path = "../agent_api_rest" }
agent_authorization = { path = "../agent_authorization", features = [
    "test_utils",
] }
agent_holder = { path = "../agent_holder", features = ["test_utils"] }
agent_identity = { path = ".", features = ["test_utils"] }
agent_issuance = { path = "../agent_issuance", features = ["test_utils"] }
agent_secret_manager = { path = "../agent_secret_manager", features = [
    "test_utils",
] }
agent_shared = { path = "../agent_shared", features = ["test_utils"] }
agent_store = { path = "../agent_store" }

axum.workspace = true
lazy_static.workspace = true
mime.workspace = true
names = { version = "0.14", default-features = false }
reqwest.workspace = true
serial_test = "3.0"
tower.workspace = true
tracing-test.workspace = true
async-std = { version = "1.5", features = ["attributes", "tokio1"] }

[features]
test_utils = ["dep:futures", "dep:rstest"]

[patch.'https://github.com/iotaledger/iota']
iota-sdk = { git = "https://github.com/impierce/iota", package = "iota-sdk", branch = "temp/fix" }
move-core-types = { git = "https://github.com/impierce/iota.git", package = "move-core-types", branch = "temp/fix" }
shared-crypto = { git = "https://github.com/impierce/iota.git", package = "shared-crypto", branch = "temp/fix" }
iota-network-stack = { git = "https://github.com/impierce/iota.git", package = "iota-network-stack", branch = "temp/fix" }
iota-types = { git = "https://github.com/impierce/iota.git", package = "iota-types", branch = "temp/fix" }
iota-metrics = { git = "https://github.com/impierce/iota.git", package = "iota-metrics", branch = "temp/fix" }
move-binary-format = { git = "https://github.com/impierce/iota.git", package = "move-binary-format", branch = "temp/fix" }
iota-protocol-config = { git = "https://github.com/impierce/iota.git", package = "iota-protocol-config", branch = "temp/fix" }
move-vm-config = { git = "https://github.com/impierce/iota.git", package = "move-vm-config", branch = "temp/fix" }
iota-adapter-latest = { git = "https://github.com/impierce/iota.git", package = "iota-adapter-latest", branch = "temp/fix" }
iota-execution = { git = "https://github.com/impierce/iota.git", package = "iota-execution", branch = "temp/fix" }
