[package]
name = "agent_identity"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
agent_shared = { path = "../agent_shared" }
agent_secret_manager = { path = "../agent_secret_manager" }
shared-kernel.workspace = true

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
chrono.workspace = true
cqrs-es.workspace = true
derivative.workspace = true
did-jwk-extern = { version = "0.1.1", package = "did-jwk" }
did-key-extern = { version = "0.2.2", package = "did-method-key" }
identity_credential.workspace = true
identity_core.workspace = true
identity_did.workspace = true
identity_document.workspace = true
identity_storage.workspace = true
identity_iota.workspace = true
iota-sdk.workspace = true
itertools = "0.14"
jsonwebtoken.workspace = true
oid4vc-core.workspace = true
oid4vci.workspace = true
product_common.workspace = true
rand.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
ssi-dids = "0.1.1"
ssi-jwk = "0.1.2"
strum.workspace = true
strum_macros.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
urlencoding = "2.1"
utoipa.workspace = true
uuid.workspace = true

# `test_utils` dependencies
futures = { workspace = true, optional = true }
rstest = { workspace = true, optional = true }

[dev-dependencies]
agent_api_http = { path = "../agent_api_http" }
agent_holder = { path = "../agent_holder", features = ["test_utils"] }
agent_identity = { path = ".", features = ["test_utils"] }
agent_issuance = { path = "../agent_issuance", features = ["test_utils"] }
agent_secret_manager = { path = "../agent_secret_manager", features = [
    "test_utils",
] }
agent_shared = { path = "../agent_shared", features = ["test_utils"] }
agent_store = { path = "../agent_store" }

async-std.workspace = true
axum.workspace = true
lazy_static.workspace = true
mime.workspace = true
names = { version = "0.14", default-features = false }
reqwest.workspace = true
serial_test = "3.0"
tower.workspace = true
tracing-test.workspace = true
wiremock.workspace = true

[features]
test_utils = ["dep:futures", "dep:rstest"]
allow-localhost = []
