[package]
name = "agent_authorization"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agent_identity = { path = "../agent_identity" }
agent_issuance = { path = "../agent_issuance" }
agent_shared = { path = "../agent_shared" }
agent_secret_manager = { path = "../agent_secret_manager" }

anyhow.workspace = true
async-trait.workspace = true
cqrs-es.workspace = true
chrono.workspace = true
jsonwebtoken.workspace = true
oid4vci.workspace = true
oid4vc-core.workspace = true
strum.workspace = true
strum_macros.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
url.workspace = true
urlencoding = "2.1"
uuid.workspace = true

# `test_utils` dependencies
lazy_static = { workspace = true, optional = true }
once_cell = { workspace = true, optional = true }
rstest = { workspace = true, optional = true }

[dev-dependencies]
agent_holder = { path = "../agent_holder", features = ["test_utils"] }
agent_authorization = { path = ".", features = ["test_utils"] }
agent_secret_manager = { path = "../agent_secret_manager", features = [
    "test_utils",
] }
agent_shared = { path = "../agent_shared", features = ["test_utils"] }
async-std.workspace = true
serial_test = "3.0"
tracing-test.workspace = true

[features]
test_utils = ["dep:lazy_static", "dep:once_cell", "dep:rstest"]
