[package]
name = "agent_secret_manager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agent_shared = { path = "../agent_shared" }

# TODO: Fully remove `did_manager`.
# - The `producer` module has already been eliminated.
# - In the `consumer` module, only the `Resolver` struct is still in use.
# - All components of the `identity_stronghold_ext` module are still active.
# FIXME: make sure to use a tag for these dependencies.
# Future work: Migrate the remaining functionality into UniCore.
# did_manager_consumer = { git = "https://github.com/impierce/did-manager", tag = "v1.0.0-beta.6", package = "consumer" }
# did_manager_identity_stronghold_ext = { git = "https://github.com/impierce/did-manager", tag = "v1.0.0-beta.6", package = "identity_stronghold_ext" }
did_manager_consumer = { git = "https://github.com/impierce/did-manager", rev = "d730318", package = "consumer" }
did_manager_identity_stronghold_ext = { git = "https://github.com/impierce/did-manager", rev = "d730318", package = "identity_stronghold_ext" }
# did_manager_consumer = { path = "../../did-manager/consumer", package = "consumer" }
# did_manager_identity_stronghold_ext = { path = "../../did-manager/identity_stronghold_ext", package = "identity_stronghold_ext" }

anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
futures.workspace = true
identity_iota.workspace = true
iota-sdk.workspace = true
iota-sdk-legacy.workspace = true
iota_stronghold = { version = "2.1" }
itertools = "0.14"
jsonwebtoken = "9.3"
log = "0.4"
oid4vc-core.workspace = true
p256 = { version = "0.13", features = ["jwk"] }
serde.workspace = true
strum.workspace = true
tokio.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
agent_shared = { path = "../agent_shared", features = ["test_utils"] }

futures.workspace = true
lazy_static.workspace = true
ring = "0.17.8"

[features]
test_utils = []
