[package]
name = "agent_secret_manager"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
agent_shared = { path = "../agent_shared" }

# TODO: Fully remove `did_manager`.
# - The `producer` module has already been eliminated.
# - In the `consumer` module, only the `Resolver` struct is still in use.
# - All components of the `identity_stronghold_ext` module are still active.
#
# Future work: Migrate the remaining functionality into UniCore.
did_manager_consumer = { git = "https://git@github.com/impierce/did-manager.git", rev = "5a5c124", package = "consumer" }
did_manager_identity_stronghold_ext = { git = "https://git@github.com/impierce/did-manager.git", rev = "5a5c124", package = "identity_stronghold_ext" }

anyhow = "1.0"
async-trait = "0.1"
base64.workspace = true
did-jwk-extern = { version = "0.1.1", package = "did-jwk" }
did-key-extern = { version = "0.2.2", package = "did-method-key" }
futures.workspace = true
identity_iota.workspace = true
iota-sdk.workspace = true
iota_stronghold = { version = "2.1" }
itertools = "0.14"
jsonwebtoken = "9.3"
log = "0.4"
oid4vc-core.workspace = true
p256 = { version = "0.13", features = ["jwk"] }
serde_json.workspace = true
ssi-dids = "0.1.1"
ssi-jwk = "0.1.2"
tokio.workspace = true
url.workspace = true

[dev-dependencies]
agent_shared = { path = "../agent_shared", features = ["test_utils"] }

futures.workspace = true
lazy_static.workspace = true
ring = "0.17.8"

[features]
test_utils = []
