server {
    listen 80;
    server_name example.com;

    location /some/path/ {
        proxy_pass http://ssi-agent:3033/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Default catch-all that forwards to the same endpoint path on the container
    location / {
        proxy_pass http://ssi-agent:3033/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}

server {
    listen 80;
    server_name some-thing-else.com;

    # Default catch-all that forwards to the same endpoint path on the container
    location / {
        proxy_pass http://ssi-agent:3033/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
