name: Format, Lint, Test

on:
  pull_request:
    branches:
      - main
      - next
      - beta
      - alpha

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Format
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Test
        run: RUST_MIN_STACK=16777216 cargo test --workspace
