# The title of the pull request is used as the commit message when working with a squash-based merging style.
# This project also follows semantic versioning, so it is important that the title follows conventional commits and should therefore be checked.

name: Lint PR title

on:
  pull_request:
    branches:
      - main
      - next
      - beta
      - alpha
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    # types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - run: npm install -g @commitlint/config-angular

      - run: echo $TITLE | npx commitlint
        env:
          # Security: we mitigate script injections by using an intermediate environment variable
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TITLE: ${{ github.event.pull_request.title }}
